### PR TITLE
Use simple HTML5 to show/hide the controls

### PR DESCRIPTION
**Pull request by sjbrown**

### CODE REVIEW

**Comment by sjbrown** [comment]
Hmm... I could try...

**Comment by sjbrown** [comment]
How's that?

**Comment by shanel** [comment]
Seems to be an issue: https://imgur.com/a/u8Z6QFb

**Comment by sjbrown** [comment]
The missing characters? I'm guessing the font that browser's using doesn't have them.  We might be able to force the font face by using a web font.

What browser is that?

**Comment by shanel** [comment]
Chrome on Mac.

**Comment by sjbrown** [comment]
Ok, I can access one of those later on today, I'll see if I can reproduce & fix

**Comment by sjbrown** [comment]
How's that?

**Comment by shanel** [comment]
I did a couple tweaks and feel this works a bit better (not sure how to actually give you those tweaks, but think you will be able to figure them out):

screen shot 2018-10-25 at 6 38 39 pm

**Comment by sjbrown** [comment]
not sure I understand - did you make a code change, or a mockup?

**Comment by shanel** [comment]
I made code changes locally. Moved the safety tools below instead of above, went with white background for the summary and center aligned them as well. Removed the "Controls" word and the icons after "Safety Tools." And set the safety tools details open by default.

**Comment by sjbrown** [comment]
sounds good. so you could either:
1) accept my pull request, then apply your changes
2) send me your changes and then I'll add them to my pull request

**Comment by shanel** [comment]
It'll be a little bit before I push this out since I am doing some more stuff re: safety tools. But I will let you know when I push it.

**Pull request merged**
